use DBPolifemo

INSERT INTO Types VALUES (null, "Festivo");                /*1*/
INSERT INTO Types VALUES (null, "Esame");                  /*2*/
INSERT INTO Types VALUES (null, "Esame di Profitto");      /*3*/
INSERT INTO Types VALUES (null, "Lauree Magistrali");      /*4*/
INSERT INTO Types VALUES (null, "Lezione");                /*5*/
INSERT INTO Types VALUES (null, "Sabato");                 /*6*/
INSERT INTO Types VALUES (null, "Lauree 1 liv");           /*7*/
INSERT INTO Types VALUES (null, "Vacanza");                /*8*/
INSERT INTO Types VALUES (null, "Altre attività");         /*9*/