use
DBPolifemo

INSERT INTO Types VALUES (null, "Festivo");                /*1 fatto parzialmente*/
INSERT INTO Types VALUES (null, "Esame");                  /*2*/
INSERT INTO Types VALUES (null, "Esame di Profitto");      /*3 fatto*/
INSERT INTO Types VALUES (null, "Lauree Magistrali");      /*4 fatto*/
INSERT INTO Types VALUES (null, "Lezione");                /*5 fatto*/
INSERT INTO Types VALUES (null, "Sabato");                 /*6 fatto*/
INSERT INTO Types VALUES (null, "Lauree 1 liv");           /*7 fatto*/
INSERT INTO Types VALUES (null, "Vacanza");                /*8 fatto*/
INSERT INTO Types VALUES (null, "Altre attività");         /*9 fatto*/