use
DBPolifemo

INSERT INTO tipologia VALUES (null, "Festivo");                /*1 fatto parzialmente*/
INSERT INTO tipologia
VALUES (null, "Esame"); /*2*/
INSERT INTO tipologia
VALUES (null, "Esame di Profitto"); /*3 fatto*/
INSERT INTO tipologia
VALUES (null, "Lauree Magistrali"); /*4 fatto*/
INSERT INTO tipologia
VALUES (null, "Lezione"); /*5 fatto*/
INSERT INTO tipologia
VALUES (null, "Sabato"); /*6 fatto*/
INSERT INTO tipologia
VALUES (null, "Lauree 1 liv"); /*7 fatto*/
INSERT INTO tipologia
VALUES (null, "Vacanza"); /*8 fatto*/
INSERT INTO tipologia
VALUES (null, "Altre attività"); /*9 fatto*/