name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and release

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build PoliFemoBackend.csproj /p:DeployOnBuild=true /p:Configuration=Release /p:Platform="x64" /p:PublishProfile=Properties/PublishProfiles/linux-x64.pubxml
      
    - name: Get current date
      continue-on-error: true
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"
  
  
  
  deploy:

    needs: build
    runs-on: ubuntu-latest
    name: Deploy

    steps:
    - name: Wait
      continue-on-error: true
      run: sleep 10
      
    - name: Deploy
      run: curl -m 10 https://api.polinetwork.org/v1/DeployLatest?token=${{ secrets.TOKEN_UPGRADE }}

    - name: Wait
      continue-on-error: true
      run: sleep 20
      
    - name: Get uptime
      id: uptime
      run: echo "::set-output name=uptime::$(curl https://api.polinetwork.org/v1/GetUptime)"
      
    - name: Check whether the deployment was successful
      continue-on-error: true
      if: ${{ steps.uptime.outputs.uptime > 120 }}
      uses: actions/github-script@v6
      with:
        script: core.setFailed('Deploy failed')
